// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-VTMXxsKeeg5MmFpC3pbkdTFyGfynU54',
    appId: '1:556729817485:web:fb75c3ede0005fb62b45c4',
    messagingSenderId: '556729817485',
    projectId: 'subbies-app',
    authDomain: 'subbies-app.firebaseapp.com',
    storageBucket: 'subbies-app.firebasestorage.app',
    measurementId: 'G-GTCZJ50NLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZPMXt0blgDLVb9ncnMyz2EUfx6vDQqI',
    appId: '1:556729817485:android:234c8d6063e3d4cd2b45c4',
    messagingSenderId: '556729817485',
    projectId: 'subbies-app',
    storageBucket: 'subbies-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiA3XxaEJ_UuSCUJsWwGiii3sTD3eaIlw',
    appId: '1:556729817485:ios:b97f3b56d6b3eba42b45c4',
    messagingSenderId: '556729817485',
    projectId: 'subbies-app',
    storageBucket: 'subbies-app.firebasestorage.app',
    iosBundleId: 'com.example.subbies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiA3XxaEJ_UuSCUJsWwGiii3sTD3eaIlw',
    appId: '1:556729817485:ios:ab2055e80d2305632b45c4',
    messagingSenderId: '556729817485',
    projectId: 'subbies-app',
    storageBucket: 'subbies-app.firebasestorage.app',
    iosBundleId: 'com.prajwal.recurring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-VTMXxsKeeg5MmFpC3pbkdTFyGfynU54',
    appId: '1:556729817485:web:105c33703558a1b02b45c4',
    messagingSenderId: '556729817485',
    projectId: 'subbies-app',
    authDomain: 'subbies-app.firebaseapp.com',
    storageBucket: 'subbies-app.firebasestorage.app',
    measurementId: 'G-L0E7EDNDJ4',
  );
}
